version: "3"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: sentinel
    container_name: sentinel
    restart: unless-stopped
    volumes:
      - .:/var/www/html
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=sentinel
      - DB_USERNAME=sentinel
      - DB_PASSWORD=password
    ports:
      - "8000:8000" # Map port 8000 on the host to port 9000 in the container (adjust as needed)
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: sentinel_database
    restart: unless-stopped
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=sentinel
      - MYSQL_USER=sentinel
      - MYSQL_PASSWORD=password

volumes:
  mysql_data:
